spring:
  application:
    name: activity-service

  config:
    import: optional:file:.env[.properties]

  mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
server:
  port: 8082
